control_node: {
  control_is_on: false,
  joint_angle_desired: [-0.155, 0.126, -1.638, 1.509, -1.418, 1.538, -1.40],
  cartesian_pose_desired: [0,0,0,0,0,0],
  joint_velocity_desired: [0,0,0,0,0,0,0],
  selected_filter_number: 3,
  Kd_upper_limit: [100,80,60,20,10,10,10],
  Kd_lower_limit: [10,10,10,10,10,10,10,],
  Dd_upper_limit: [1],
  Dd_lower_limit: [1],
  Lowpass_coeff: 0.6,
  move2neutral: false,
  suppress_self_collision_detection: false,
  suppress_contact_collision_detection: false,
}

oscillation_guard: {
  window_length: 30,
  corner_frequency: 10,
  magnitude_limit: 12,
}

nullspace: {
  is_locked: false,
  jointspace_pose: [-0.155, 0.126, -1.638, 1.509, -1.418, 1.538, -1.40],
}
named_poses: {
  right: {
    poses: {
      neutral: [-0.155, 0.126, -1.638, 1.509, -1.418, 1.538, -1.40],
    }
  }
}
